# Generated by Django 4.2.1 on 2023-05-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_income_member_remove_income_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='whatsapp_line',
        ),
    ]
